### ISSUE TITLE
Consider gpg signing the releases

### ISSUE THREAD

**Issue by nolim1t** [lncm/docker-lnd#10]
Might be a good idea in future and to also be something to put in box installs later

**Comment by meeDamian** [comment]
You mean on Travis?

**Comment by nolim1t** [comment]
no when you create a release with LND binaries as good practice with open source. 

That way we can probably stop using docker-hub and just fetch and verify the tarballs instead and avoid stuff like [this](https://news.ycombinator.com/item?id=19763413) which may compromise trust

**Comment by meeDamian** [comment]
All of my tags are signed, and timestamped, example:

```bash
$ cd docker-lnd/

$ git cat-file tag 0.6.0
object d4d0d445ac774abadf5a2e0228a5515172b74b34
type commit
tag 0.6.0
tagger Damian Mee <spam@meedamian.com> 1556455341 +0700

0.6.0
-----BEGIN PGP SIGNATURE-----

iHUEABYKAB0WIQTtY4HsLQy75kGOKekvlh6rh4lyXQUCXMWfrgAKCRAvlh6rh4ly
XSLnAP4pf6P2Tg5V1yV82NnRRLm8j5p0U7+eZ3vyuBT1QbozWgD+JM6D+I5O8gXb
eY9WLGUP9R2yTccg/tJakalg+yoJ3wU=
=h00d
-----END PGP SIGNATURE-----
-----BEGIN OPENTIMESTAMPS GIT TIMESTAMP-----

AQHwIO1a2Bw+g2Rrg+Uc+zLPPVksnc6mLu5cTJTGhUv8CUUJCP/wEE1pO1TphBL1
799PlQmaarkI8QRcxZ+w8AhkygGoVoMSKwCD3+MNLvkMji4taHR0cHM6Ly9hbGlj
ZS5idGMuY2FsZW5kYXIub3BlbnRpbWVzdGFtcHMub3Jn//AQbeY3aaLUBmSukanr
dIeVtAjxBFzFn7DwCLokLePuYXYpAIPf4w0u+QyOLCtodHRwczovL2JvYi5idGMu
Y2FsZW5kYXIub3BlbnRpbWVzdGFtcHMub3Jn//AQkeGrQ/LLYhbwDI4TrGkRDwjx
BFzFn7DwCECz+6Gre2dGAIPf4w0u+QyOIyJodHRwczovL2J0Yy5jYWxlbmRhci5j
YXRhbGxheHkuY29t8BDYkr6jIPXzaGq4oWngimxHCPAQlj+nv1ztgvA+l9IqvNA9
/gjxIHNvBdy57818+mNtlPgIx8OAPMR+wijfuJX49UF5KBiMCPEEXMWfr/AI61FK
Vw+l1y8Ag9/jDS75DI4pKGh0dHBzOi8vZmlubmV5LmNhbGVuZGFyLmV0ZXJuaXR5
d2FsbC5jb20=
-----END OPENTIMESTAMPS GIT TIMESTAMP-----

$ git tag -v 0.6.0
object d4d0d445ac774abadf5a2e0228a5515172b74b34
type commit
tag 0.6.0
tagger Damian Mee <spam@meedamian.com> 1556455341 +0700

0.6.0
ots: Got 1 attestation(s) from https://alice.btc.calendar.opentimestamps.org
ots: Got 1 attestation(s) from https://bob.btc.calendar.opentimestamps.org
ots: Got 1 attestation(s) from https://btc.calendar.catallaxy.com
ots: Got 1 attestation(s) from https://finney.calendar.eternitywall.com
ots: Success! Bitcoin block 573619 attests existence as of 2019-04-28 +07
ots: Good timestamp
gpg: Signature made Sun Apr 28 19:42:22 2019 +07
gpg:                using EDDSA key ED6381EC2D0CBBE6418E29E92F961EAB8789725D
gpg: Good signature from "Damian Mee (https://meedamian.com) <spam@meedamian.com>" [ultimate]
gpg:                 aka "Damian Mee (https://meedamian.com) <mee.damian@gmail.com>" [ultimate]
gpg:                 aka "keybase.io/meedamian <meedamian@keybase.io>" [ultimate]
gpg:                 aka "[jpeg image of size 10005]" [ultimate]
gpg:                 aka "Damian Mee <meedamian@protonmail.com>" [ultimate]
```

After a push of a _signed_ tag to Github, Travis picks it up, builds all desired architectures, and does two things:
1. pushes images to Docker Hub and aggregates them into manifests, and
1. extracts images into tarballs that are uploaded to the corresponding Github release, example: https://github.com/lncm/docker-lnd/releases/tag/0.6.0

I'm not sure if signing anything on Travis makes sense, because you already trust Travis to be honest, and there's no benefit in uploading any private key to travis to do placebo signing.  Also, signing tarballs that were produced by Travis is quite pointless & dishonest, as you'd be signing on the fact that Travis is honest, but we have no way to guarantee it beyond what anyone else can.

PS. I do the exact same with `invoicer` except I don't upload docker images to releases but plain Go binaries.

Does that address your issue?
